import { ThemeProvider } from "@/theme-context";
import "./globals.css";
import { Roboto_Flex as Roboto } from "next/font/google";
import { useContext } from "react";

const roboto = Roboto({ subsets: ["latin"], variable: "--font-roboto" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <>{children}</>
      </ThemeProvider>
    </html>
  );
}
